#' Shared parameter documentation
#'
#' @param org A single character string giving the GitHub organisation or
#'   username whose repositories should be retrieved.
#' @param limit The maximum number of repositories to retrieve. The default is
#'   `Inf`, which retrieves all available repositories.
#' @param token A GitHub installation access token or personal access token.
#'   The default is `get_token()`, which returns a token generated by
#'   the GitHub App.
#' @param repos A character vector of repository names, or a data frame with a
#'   column named `repo_name`.
#'   If a data frame is supplied without this column, an error is raised.
#' @param list A list produced from the corresponding get_ function.
#' @param repo A single repository name.
#'
#'
#' @keywords internal
shared_params <- function(org, limit, token, repos) {}
